/*
 * wallet account constants
 */

module.exports = {
  SET_WALLET_ACCOUNT_INFO: 'SET_WALLET_ACCOUNT_INFO',
  SET_WALLET_ACCOUNT_BALANCE: 'SET_WALLET_ACCOUNT_BALANCE',
  SET_WALLET_ACCOUNTS: 'SET_WALLET_ACCOUNTS',
  USER_SELECT_ACCOUNT: 'USER_SELECT_ACCOUNT',
  WALLET_CREATE_ACCOUNT: 'WALLET_CREATE_ACCOUNT',
};

