/*
 * application wide constants
 */

export const USER_SELECT_XPUB = 'USER_SELECT_XPUB';
export const USER_SELECT_WALLET = 'USER_SELECT_WALLET';
export const USER_SELECT_MULTISIG_PROPOSAL = 'USER_SELECT_MULTISIG_PROPOSAL';
export const USER_SELECT_ACCOUNT = 'USER_SELECT_ACCOUNT';
export const USER_SELECT_MULTISIG_WALLET = 'USER_SELECT_MULTISIG_WALLET';
export const UPDATE_TEXT_FIELD = 'UPDATE_TEXT_FIELD';
