/*
 * application wide constants
 */

module.exports = {
  USER_SELECT_XPUB: 'USER_SELECT_XPUB',
  USER_SELECT_MULTISIG_PROPOSAL: 'USER_SELECT_MULTISIG_PROPOSAL',
  USER_SELECT_ACCOUNT: 'USER_SELECT_ACCOUNT',
  USER_SELECT_MULTISIG_WALLET: 'USER_SELECT_MULTISIG_WALLET',
};
