/*
 * wallet constants
 */

module.exports = {
  SET_WALLET_HISTORY: 'SET_WALLET_HISTORY',
  SET_WALLETS: 'SET_WALLETS',
  SET_WALLET_ACCOUNTS: 'SET_WALLET_ACCOUNTS',
  USER_SELECT_WALLET: 'USER_SELECT_WALLET',
  USER_SELECT_ACCOUNT: 'USER_SELECT_ACCOUNT',
  SET_WALLET_INFO: 'SET_WALLET_INFO',
  SET_WALLET_ACCOUNT_INFO: 'SET_WALLET_ACCOUNT_INFO',
  SET_WALLET_ACCOUNT_BALANCE: 'SET_WALLET_ACCOUNT_BALANCE',
};
