/*
 * wallet constants
 */

export const SET_WALLETS = 'SET_WALLETS';
export const SET_WALLET_ACCOUNTS = 'SET_WALLET_ACCOUNTS';
export const SET_WALLET_INFO = 'SET_WALLET_INFO';
export const SET_WALLET_ACCOUNT_INFO = 'SET_WALLET_ACCOUNT_INFO';
export const SET_WALLET_ACCOUNT_BALANCE = 'SET_WALLET_ACCOUNT_BALANCE';
export const SET_MULTISIG_PROPOSAL_MTX = 'SET_MULTISIG_PROPOSAL_MTX';
export const SET_MULTISIG_WALLETS = 'SET_MULTISIG_WALLETS';
export const SET_MULTISIG_WALLET_INFO = 'SET_MULTISIG_WALLET_INFO';
export const SET_MULTISIG_WALLET_ACCOUNTS = 'SET_MULTISIG_WALLET_ACCOUNTS';
export const SET_WALLET_HISTORY = 'SET_WALLET_HISTORY';
export const SET_MULTISIG_WALLET_ACCOUNT_INFO =
  'SET_MULTISIG_WALLET_ACCOUNT_INFO';
