version: 2
jobs:
  install:
    docker:
      - image: node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: install os deps
          command: |
            apt-get update
            apt-get install -y libudev-dev apt-utils libusb-1.0-0-dev \
              libssl-dev build-essential

      - run:
          name: install npm deps
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: node:10.9.0

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: install os deps
          command: |
            apt-get update
            apt-get install -y libudev-dev apt-utils libusb-1.0-0-dev \
              libssl-dev build-essential

      - run:
          name: install npm deps
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: npm run test

  lint:
    docker:
        - image: node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install

      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
