version: 2
jobs:
  install:
    docker:
      - image: node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
        - image: node:10.9.0
          environment:
            CHROME_BIN: /usr/bin/google-chrome

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: install os deps
          command: |
            curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
            && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
            && apt-get update \
            && apt-get install -y libudev-dev apt-utils libusb-1.0-0-dev \
              libssl-dev google-chrome-stable build-essential openssh-server

      - run:
          name: install npm deps
          command: npm install

      - run:
          name: install peer deps
          command: npm run installPeerDeps

      - run:
          name: create ssl certs
          command: make ssl

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: npm run test

      - run:
          name: run browser tests
          command: npm run test-browser

  lint:
    docker:
        - image: node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          - v2-dependencies-

      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
