const {
  updateTextField,
  addSideNav,
  selectTab,
  removeSideNav,
} = require('./interface');

const {
  getWallets,
  selectWallet,
  createWallet,
  getWalletInfo,
  getWalletsInfo,
  sendTX,
  joinWallet,
  getxpubCreateMultisigWallet,
  getxpubCreateWatchOnlyWallet,
  setTemporarySecrets,
  getMultisigProposals,
  createProposal,
  approveProposal,
  rejectProposal,
  clearAllWallets,
  selectProposal,
  broadcastTransaction,
  sendProposal,
} = require('./wallet');

const {
  selectAccount,
  createAddress,
  createAccount,
  getxpubCreateWatchOnly,
  getAccountHistory,
} = require('./account');

module.exports = {
  clearAllWallets,
  createAddress,
  createProposal,
  createAccount,
  addSideNav,
  removeSideNav,
  joinWallet,
  updateTextField,
  getAccountHistory,
  getWallets,
  getWalletsInfo,
  getWalletInfo,
  selectWallet,
  selectAccount,
  createWallet,
  sendTX,
  broadcastTransaction,
  sendProposal,
  getxpubCreateWatchOnly, // watch only account
  getxpubCreateWatchOnlyWallet,
  getxpubCreateMultisigWallet,
  setTemporarySecrets,
  getMultisigProposals,
  approveProposal,
  rejectProposal,
  selectProposal,
  selectTab,
};
