#!/bin/bash

BCOIN_API_KEY=
BCOIN_HTTP_HOST=
BCOIN_NODE_PORT=
BCOIN_WALLET_PORT=
BCOIN_ADMIN_TOKEN=
BCOIN_NODE_URL=
BCOIN_NETWORK=
BCOIN_WALLET_HTTP_HOST=

# BCOIN_MULTISIG_API_KEY=
# BCOIN_NODE_API_KEY=
# BCOIN_MULTISIG_ADMIN_TOKEN=
# BCOIN_MULTISIG_HTTP_HOST=
# BCOIN_NODE_HOST=
# BCOIN_WALLET_WALLET_AUTH=true

